version: "3.7"

services:
    web:
        container_name: web
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - nginx
        networks:
            - netcoins.dev

    nginx:
        container_name: nginx
        image: nginx:1.21.6
        working_dir: /var/www/html
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - netcoins.dev

networks:
    netcoins.dev:
        driver: bridge
